// <auto-generated />
using System;
using JobProcessor.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobProcessor.Migrations
{
    [DbContext(typeof(JobDbContext))]
    [Migration("20260224135205_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("JobProcessor.Core.Patient", b =>
                {
                    b.Property<long>("PatientId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PatientId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("JobProcessor.Core.Sample", b =>
                {
                    b.Property<long>("SampleId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint");

                    b.Property<string>("SampleType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("SampleId");

                    b.HasIndex("PatientId");

                    b.ToTable("Samples");
                });

            modelBuilder.Entity("JobProcessor.Core.TestOrder", b =>
                {
                    b.Property<long>("TestOrderId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("int");

                    b.Property<string>("Payload")
                        .HasColumnType("longtext");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<long>("SampleId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TestOrderType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("TestOrderId");

                    b.HasIndex("SampleId");

                    b.ToTable("TestOrders");
                });

            modelBuilder.Entity("JobProcessor.Core.TestResult", b =>
                {
                    b.Property<long>("TestResultId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ResultValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("TestOrderId")
                        .HasColumnType("bigint");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("TestResultId");

                    b.HasIndex("TestOrderId")
                        .IsUnique();

                    b.ToTable("TestResults");
                });

            modelBuilder.Entity("JobProcessor.Core.Sample", b =>
                {
                    b.HasOne("JobProcessor.Core.Patient", "Patient")
                        .WithMany("Samples")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("JobProcessor.Core.TestOrder", b =>
                {
                    b.HasOne("JobProcessor.Core.Sample", "Sample")
                        .WithMany("TestOrders")
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sample");
                });

            modelBuilder.Entity("JobProcessor.Core.TestResult", b =>
                {
                    b.HasOne("JobProcessor.Core.TestOrder", "TestOrder")
                        .WithOne("TestResult")
                        .HasForeignKey("JobProcessor.Core.TestResult", "TestOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestOrder");
                });

            modelBuilder.Entity("JobProcessor.Core.Patient", b =>
                {
                    b.Navigation("Samples");
                });

            modelBuilder.Entity("JobProcessor.Core.Sample", b =>
                {
                    b.Navigation("TestOrders");
                });

            modelBuilder.Entity("JobProcessor.Core.TestOrder", b =>
                {
                    b.Navigation("TestResult");
                });
#pragma warning restore 612, 618
        }
    }
}
